-- ============================================================
-- Musical Instruments Store
-- Initial Database Schema
-- ============================================================

-- ============================================================
-- 1. PROFILES
-- ============================================================

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    email text,
    phone text,
    role text not null default 'customer'
        check (role in ('customer', 'admin')),
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 2. CATEGORIES
-- ============================================================

create table public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    description text,
    image_url text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 3. PRODUCTS
-- ============================================================

create table public.products (
    id bigint generated by default as identity primary key,
    category_id bigint references public.categories(id) on delete set null,
    name text not null,
    slug text not null unique,
    sku text not null unique,
    brand text,
    description text,
    price numeric(12,2) not null check (price >= 0),
    discount_price numeric(12,2)
        check (discount_price is null or discount_price >= 0),
    stock_quantity integer not null default 0
        check (stock_quantity >= 0),
    is_featured boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint valid_discount_price
        check (
            discount_price is null
            or discount_price <= price
        )
);


-- ============================================================
-- 4. PRODUCT IMAGES
-- ============================================================

create table public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null
        references public.products(id) on delete cascade,
    image_url text not null,
    alt_text text,
    is_primary boolean not null default false,
    display_order integer not null default 0,
    created_at timestamptz not null default now()
);


-- ============================================================
-- 5. PRODUCT SPECIFICATIONS
-- ============================================================

create table public.product_specifications (
    id bigint generated by default as identity primary key,
    product_id bigint not null
        references public.products(id) on delete cascade,
    specification_name text not null,
    specification_value text not null,
    created_at timestamptz not null default now()
);


-- ============================================================
-- 6. ADDRESSES
-- ============================================================

create table public.addresses (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references public.profiles(id) on delete cascade,
    name text not null,
    phone text not null,
    address text not null,
    city text not null,
    state text not null,
    postal_code text not null,
    country text not null default 'India',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 7. CART ITEMS
-- ============================================================

create table public.cart_items (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references public.profiles(id) on delete cascade,
    product_id bigint not null
        references public.products(id) on delete cascade,
    quantity integer not null default 1
        check (quantity > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint unique_cart_product
        unique (user_id, product_id)
);


-- ============================================================
-- 8. WISHLISTS
-- ============================================================

create table public.wishlists (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique
        references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now()
);


-- ============================================================
-- 9. WISHLIST ITEMS
-- ============================================================

create table public.wishlist_items (
    id bigint generated by default as identity primary key,
    wishlist_id bigint not null
        references public.wishlists(id) on delete cascade,
    product_id bigint not null
        references public.products(id) on delete cascade,
    created_at timestamptz not null default now(),

    constraint unique_wishlist_product
        unique (wishlist_id, product_id)
);


-- ============================================================
-- 10. ORDERS
-- ============================================================

create table public.orders (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references public.profiles(id) on delete restrict,
    order_number text not null unique,
    status text not null default 'Pending'
        check (
            status in (
                'Pending',
                'Confirmed',
                'Processing',
                'Shipped',
                'Delivered',
                'Cancelled'
            )
        ),
    subtotal numeric(12,2) not null
        check (subtotal >= 0),
    shipping_fee numeric(12,2) not null default 0
        check (shipping_fee >= 0),
    total_amount numeric(12,2) not null
        check (total_amount >= 0),

    shipping_name text,
    shipping_phone text,
    shipping_address text,
    shipping_city text,
    shipping_state text,
    shipping_postal_code text,
    shipping_country text,

    payment_method text,
    payment_status text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 11. ORDER ITEMS
-- ============================================================

create table public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null
        references public.orders(id) on delete cascade,
    product_id bigint
        references public.products(id) on delete set null,
    product_name text not null,
    quantity integer not null
        check (quantity > 0),
    unit_price numeric(12,2) not null
        check (unit_price >= 0),
    subtotal numeric(12,2) not null
        check (subtotal >= 0),
    created_at timestamptz not null default now()
);


-- ============================================================
-- 12. REVIEWS
-- ============================================================

create table public.reviews (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references public.profiles(id) on delete cascade,
    product_id bigint not null
        references public.products(id) on delete cascade,
    order_id bigint
        references public.orders(id) on delete set null,
    rating integer not null
        check (rating between 1 and 5),
    comment text,
    status text not null default 'pending'
        check (
            status in (
                'pending',
                'approved',
                'rejected',
                'hidden'
            )
        ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 13. CONTACT MESSAGES
-- ============================================================

create table public.contact_messages (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text,
    subject text not null,
    message text not null,
    status text not null default 'unread'
        check (
            status in (
                'unread',
                'read',
                'resolved',
                'archived'
            )
        ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

create index idx_products_category_id
    on public.products(category_id);

create index idx_products_brand
    on public.products(brand);

create index idx_products_price
    on public.products(price);

create index idx_products_stock_quantity
    on public.products(stock_quantity);

create index idx_products_is_active
    on public.products(is_active);

create index idx_products_is_featured
    on public.products(is_featured);

create index idx_product_images_product_id
    on public.product_images(product_id);

create index idx_product_specifications_product_id
    on public.product_specifications(product_id);

create index idx_addresses_user_id
    on public.addresses(user_id);

create index idx_cart_items_user_id
    on public.cart_items(user_id);

create index idx_cart_items_product_id
    on public.cart_items(product_id);

create index idx_wishlists_user_id
    on public.wishlists(user_id);

create index idx_wishlist_items_wishlist_id
    on public.wishlist_items(wishlist_id);

create index idx_wishlist_items_product_id
    on public.wishlist_items(product_id);

create index idx_orders_user_id
    on public.orders(user_id);

create index idx_orders_status
    on public.orders(status);

create index idx_orders_created_at
    on public.orders(created_at desc);

create index idx_order_items_order_id
    on public.order_items(order_id);

create index idx_order_items_product_id
    on public.order_items(product_id);

create index idx_reviews_product_id
    on public.reviews(product_id);

create index idx_reviews_user_id
    on public.reviews(user_id);

create index idx_reviews_status
    on public.reviews(status);

create index idx_contact_messages_status
    on public.contact_messages(status);


-- ============================================================
-- UPDATED_AT TRIGGER FUNCTION
-- ============================================================

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ============================================================
-- UPDATED_AT TRIGGERS
-- ============================================================

create trigger profiles_updated_at
before update on public.profiles
for each row
execute function public.handle_updated_at();

create trigger categories_updated_at
before update on public.categories
for each row
execute function public.handle_updated_at();

create trigger products_updated_at
before update on public.products
for each row
execute function public.handle_updated_at();

create trigger addresses_updated_at
before update on public.addresses
for each row
execute function public.handle_updated_at();

create trigger cart_items_updated_at
before update on public.cart_items
for each row
execute function public.handle_updated_at();

create trigger orders_updated_at
before update on public.orders
for each row
execute function public.handle_updated_at();

create trigger reviews_updated_at
before update on public.reviews
for each row
execute function public.handle_updated_at();

create trigger contact_messages_updated_at
before update on public.contact_messages
for each row
execute function public.handle_updated_at();


-- ============================================================
-- AUTO-CREATE PROFILE AFTER SUPABASE AUTH REGISTRATION
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (
        id,
        full_name,
        email
    )
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        new.email
    );

    return new;
end;
$$;


create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_specifications enable row level security;
alter table public.addresses enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlists enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;
alter table public.contact_messages enable row level security;


-- ============================================================
-- HELPER FUNCTION FOR ADMIN CHECK
-- ============================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'admin'
    );
$$;


-- ============================================================
-- PROFILE POLICIES
-- ============================================================

create policy "Users can view own profile"
on public.profiles
for select
using (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Admins can view profiles"
on public.profiles
for select
using (public.is_admin());


-- ============================================================
-- CATEGORY POLICIES
-- ============================================================

create policy "Anyone can view active categories"
on public.categories
for select
using (is_active = true or public.is_admin());

create policy "Admins can insert categories"
on public.categories
for insert
with check (public.is_admin());

create policy "Admins can update categories"
on public.categories
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete categories"
on public.categories
for delete
using (public.is_admin());


-- ============================================================
-- PRODUCT POLICIES
-- ============================================================

create policy "Anyone can view active products"
on public.products
for select
using (is_active = true or public.is_admin());

create policy "Admins can insert products"
on public.products
for insert
with check (public.is_admin());

create policy "Admins can update products"
on public.products
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete products"
on public.products
for delete
using (public.is_admin());


-- ============================================================
-- PRODUCT IMAGE POLICIES
-- ============================================================

create policy "Anyone can view product images"
on public.product_images
for select
using (
    exists (
        select 1
        from public.products p
        where p.id = product_id
          and (p.is_active = true or public.is_admin())
    )
);

create policy "Admins can insert product images"
on public.product_images
for insert
with check (public.is_admin());

create policy "Admins can update product images"
on public.product_images
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete product images"
on public.product_images
for delete
using (public.is_admin());


-- ============================================================
-- PRODUCT SPECIFICATION POLICIES
-- ============================================================

create policy "Anyone can view product specifications"
on public.product_specifications
for select
using (
    exists (
        select 1
        from public.products p
        where p.id = product_id
          and (p.is_active = true or public.is_admin())
    )
);

create policy "Admins can insert product specifications"
on public.product_specifications
for insert
with check (public.is_admin());

create policy "Admins can update product specifications"
on public.product_specifications
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete product specifications"
on public.product_specifications
for delete
using (public.is_admin());


-- ============================================================
-- ADDRESS POLICIES
-- ============================================================

create policy "Users can view own addresses"
on public.addresses
for select
using (auth.uid() = user_id);

create policy "Users can create own addresses"
on public.addresses
for insert
with check (auth.uid() = user_id);

create policy "Users can update own addresses"
on public.addresses
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own addresses"
on public.addresses
for delete
using (auth.uid() = user_id);


-- ============================================================
-- CART POLICIES
-- ============================================================

create policy "Users can view own cart"
on public.cart_items
for select
using (auth.uid() = user_id);

create policy "Users can add to own cart"
on public.cart_items
for insert
with check (auth.uid() = user_id);

create policy "Users can update own cart"
on public.cart_items
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own cart"
on public.cart_items
for delete
using (auth.uid() = user_id);


-- ============================================================
-- WISHLIST POLICIES
-- ============================================================

create policy "Users can view own wishlist"
on public.wishlists
for select
using (auth.uid() = user_id);

create policy "Users can create own wishlist"
on public.wishlists
for insert
with check (auth.uid() = user_id);

create policy "Users can update own wishlist"
on public.wishlists
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own wishlist"
on public.wishlists
for delete
using (auth.uid() = user_id);


-- ============================================================
-- WISHLIST ITEM POLICIES
-- ============================================================

create policy "Users can view own wishlist items"
on public.wishlist_items
for select
using (
    exists (
        select 1
        from public.wishlists w
        where w.id = wishlist_id
          and w.user_id = auth.uid()
    )
);

create policy "Users can add own wishlist items"
on public.wishlist_items
for insert
with check (
    exists (
        select 1
        from public.wishlists w
        where w.id = wishlist_id
          and w.user_id = auth.uid()
    )
);

create policy "Users can delete own wishlist items"
on public.wishlist_items
for delete
using (
    exists (
        select 1
        from public.wishlists w
        where w.id = wishlist_id
          and w.user_id = auth.uid()
    )
);


-- ============================================================
-- ORDER POLICIES
-- ============================================================

create policy "Users can view own orders"
on public.orders
for select
using (
    auth.uid() = user_id
    or public.is_admin()
);

create policy "Users can create own orders"
on public.orders
for insert
with check (auth.uid() = user_id);

create policy "Admins can update orders"
on public.orders
for update
using (public.is_admin())
with check (public.is_admin());


-- ============================================================
-- ORDER ITEM POLICIES
-- ============================================================

create policy "Users can view own order items"
on public.order_items
for select
using (
    exists (
        select 1
        from public.orders o
        where o.id = order_id
          and (
              o.user_id = auth.uid()
              or public.is_admin()
          )
    )
);

create policy "Users can create order items for own orders"
on public.order_items
for insert
with check (
    exists (
        select 1
        from public.orders o
        where o.id = order_id
          and o.user_id = auth.uid()
    )
);

create policy "Admins can manage order items"
on public.order_items
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete order items"
on public.order_items
for delete
using (public.is_admin());


-- ============================================================
-- REVIEW POLICIES
-- ============================================================

create policy "Anyone can view approved reviews"
on public.reviews
for select
using (
    status = 'approved'
    or auth.uid() = user_id
    or public.is_admin()
);

create policy "Authenticated users can create reviews"
on public.reviews
for insert
with check (auth.uid() = user_id);

create policy "Users can update own reviews"
on public.reviews
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own reviews"
on public.reviews
for delete
using (
    auth.uid() = user_id
    or public.is_admin()
);


-- ============================================================
-- CONTACT MESSAGE POLICIES
-- ============================================================

create policy "Anyone can submit contact messages"
on public.contact_messages
for insert
with check (true);

create policy "Admins can view contact messages"
on public.contact_messages
for select
using (public.is_admin());

create policy "Admins can update contact messages"
on public.contact_messages
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete contact messages"
on public.contact_messages
for delete
using (public.is_admin());


-- ============================================================
-- END OF INITIAL SCHEMA
-- ============================================================